### ISSUE TITLE
Question about single-query

### ISSUE THREAD

**Issue by HelloWorldLTY** [ncbi/GeneGPT#1]
Hi, thanks for your work. If my understanding is correct, this is a model to improve the performance of chatGPT on solving genetic problem via prompt engineering. However, it seems that we cannot use single query for this model. Is it possible for us to achieve this target? Thanks.

**Comment by drqiaojin** [comment]
Thank you for your interest in our work!

You can modify this line to input a single question: https://github.com/ncbi/GeneGPT/blob/8198506e1ada2f917cbb8522cb97bc07b2f7882b/main.py#L126

**Comment by HelloWorldLTY** [comment]
Thanks, will try and get back to you.
