### ISSUE TITLE
keep getting "lengthError" as response

### ISSUE THREAD

**Issue by kuandannyan** [ncbi/GeneGPT#5]
Dear authors,

Impressive work and paper. We are very interested in trying the GeneGPT. We are just starting with "python main.py 001001". See below is the json file content. I checked the OpenAI API key and it should be correct since I am using it myself at this moment as well. Other than this I have been following the instruction line-by-line. Except I am using conda and OpenAI was installed explicitly using pip-command from conda, but OpenAI version is given as stated in the requirement.txt file.

Did I mess up something? Thank you in advance.

```json
This is content of "Gene alias.json"
[
    [
        "What is the official gene symbol of LMP10?",
        "PSMB10",
        "lengthError",
        []
    ],
    [
        "What is the official gene symbol of SNAT6?",
        "SLC38A6",
        "lengthError",
        []
    ],
]
```

```json
This is content of "Gene location.json"
[
    [
        "Which chromosome is FAM66D gene located on human genome?",
        "chr8",
        "lengthError",
        []
    ],
    [
        "Which chromosome is TTTY7 gene located on human genome?",
        "chrY",
        "lengthError",
        []
    ],
]
```

Best Regards

Kuan Yan

**Comment by mbeavitt** [comment]
use main_turbo.py instead. davinci 002 used in main.py is deprecated.

specifically: python main_turbo.py 001001

You can also switch to gpt-4 or gpt-4-turbo by editing the relevant line in main_turbo.py.
